import { useState } from 'react';
import type { CustomFaceGroupSummary } from '@/api/tauriApi';
import { CUSTOM_FACE_CONTRACT } from '@/domain/customFaces/generated/customFaceContract.generated';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

type Props = { groups: CustomFaceGroupSummary[]; onOpen: (groupId: string) => void; onCreate: (profileId: string) => void; onCopy: (groupId: string) => void; onResizeCopy: (groupId: string, profileId: string) => void; onRename: (groupId: string) => void; onDelete: (groupId: string) => void };

export function CustomFaceGroupLibrary({ groups, onOpen, onCreate, onCopy, onResizeCopy, onRename, onDelete }: Props) {
  const [targetProfileId, setTargetProfileId] = useState(CUSTOM_FACE_CONTRACT.profiles[0].id as string);
  const target = CUSTOM_FACE_CONTRACT.profiles.find((profile) => profile.id === targetProfileId)!;
  return <main className="min-h-screen bg-background p-6 text-foreground"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-border pb-4"><div><h1 className="text-xl font-semibold">我的表情组</h1><p className="mt-1 text-sm text-muted-foreground">选择组进入编辑器；改变分辨率会创建新组，原组不变。</p></div><div className="flex items-end gap-2"><label className="text-xs text-muted-foreground">目标分辨率<Select value={targetProfileId} onValueChange={setTargetProfileId}><SelectTrigger aria-label="目标分辨率" className="mt-1 min-w-56 bg-background text-foreground"><SelectValue /></SelectTrigger><SelectContent>{CUSTOM_FACE_CONTRACT.profiles.map((profile) => <SelectItem key={profile.id} value={profile.id}>{profile.width} × {profile.height} · 最多 {profile.maxFrames} 帧</SelectItem>)}</SelectContent></Select></label><button className="border border-border px-3 py-2 text-sm" onClick={() => onCreate(targetProfileId)}>＋ 新建组</button><button className="border border-border px-3 py-2 text-sm">导入 .ccface</button></div></header><div className="mt-2 text-xs text-muted-foreground">当前目标：{target.width} × {target.height}，每个表情最多 {target.maxFrames} 帧。</div>{groups.length === 0 ? <div className="py-20 text-center text-sm text-muted-foreground">暂无表情组</div> : <div className="mt-5 grid gap-3">{groups.map((group) => <article key={group.groupId} className="flex items-center gap-4 border border-border bg-card p-4"><div className="h-16 w-24 border border-border bg-black" /><div className="min-w-0 flex-1"><h2 className="font-medium">{group.name}</h2><p className="mt-1 text-sm text-muted-foreground">{profileLabel(group.displayProfileId)} · {group.faceCount} 个表情</p><p className="mt-1 text-xs text-muted-foreground">revision {group.revision}</p></div><div className="flex flex-wrap justify-end gap-2"><button className="border border-primary px-3 py-2 text-sm" onClick={() => onOpen(group.groupId)}>打开</button><button className="border border-border px-3 py-2 text-sm" onClick={() => onCopy(group.groupId)}>复制</button><button className="border border-border px-3 py-2 text-sm" disabled={group.displayProfileId === targetProfileId} title={group.displayProfileId === targetProfileId ? '目标分辨率与当前组相同' : `创建 ${target.width} × ${target.height} 新组`} onClick={() => onResizeCopy(group.groupId, targetProfileId)}>另存为目标分辨率</button><button className="border border-border px-3 py-2 text-sm" onClick={() => onRename(group.groupId)}>重命名</button><button className="border border-destructive px-3 py-2 text-sm text-destructive" onClick={() => onDelete(group.groupId)}>删除</button></div></article>)}</div>}</div></main>;
}

function profileLabel(profileId: string) { const profile = CUSTOM_FACE_CONTRACT.profiles.find((item) => item.id === profileId); return profile ? `${profile.width} × ${profile.height}` : profileId; }
