/* generated by firmware/tools/generate-custom-face-package-contract.mjs */
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CustomFaceProfileSpec {
    pub code: u16,
    pub id: &'static str,
    pub width: u16,
    pub height: u16,
    pub framebuffer_bytes: usize,
    pub max_frames: u8,
    pub max_group_bytes: usize,
    pub deployment_enabled: bool,
}

pub const CUSTOM_FACE_BINARY_VERSION: u16 = 1;
pub const CUSTOM_FACE_MAX_FACES_PER_GROUP: usize = 15;
pub const CUSTOM_FACE_FRAME_DURATION_DEFAULT_MS: u16 = 200;
pub const CUSTOM_FACE_FRAME_DURATION_MIN_MS: u16 = 50;
pub const CUSTOM_FACE_FRAME_DURATION_MAX_MS: u16 = 5000;
pub const CUSTOM_FACE_MANIFEST_MAGIC: [u8; 4] = *b"CCFM";
pub const CUSTOM_FACE_BLOB_MAGIC: [u8; 4] = *b"CCFB";

pub const CUSTOM_FACE_PROFILES: &[CustomFaceProfileSpec] = &[
    CustomFaceProfileSpec {
        code: 1,
        id: "custom-mono-128x32-v1",
        width: 128,
        height: 32,
        framebuffer_bytes: 512,
        max_frames: 20,
        max_group_bytes: 131_072,
        deployment_enabled: true,
    },
    CustomFaceProfileSpec {
        code: 2,
        id: "custom-mono-128x64-v1",
        width: 128,
        height: 64,
        framebuffer_bytes: 1_024,
        max_frames: 20,
        max_group_bytes: 262_144,
        deployment_enabled: false,
    },
    CustomFaceProfileSpec {
        code: 3,
        id: "custom-mono-320x240-v1",
        width: 320,
        height: 240,
        framebuffer_bytes: 9_600,
        max_frames: 10,
        max_group_bytes: 393_216,
        deployment_enabled: true,
    },
    CustomFaceProfileSpec {
        code: 4,
        id: "custom-mono-128x128-v1",
        width: 128,
        height: 128,
        framebuffer_bytes: 2_048,
        max_frames: 10,
        max_group_bytes: 262_144,
        deployment_enabled: true,
    },
];

pub fn custom_face_profile_by_id(id: &str) -> Option<CustomFaceProfileSpec> {
    if let Some(profile) = CUSTOM_FACE_PROFILES.iter().find(|profile| profile.id == id) {
        return Some(*profile);
    }
    let value = id.strip_prefix("custom-")?.strip_suffix("-v1")?;
    let (width, height) = value.split_once('x')?;
    let width = width.parse::<u16>().ok()?;
    let height = height.parse::<u16>().ok()?;
    let area = usize::from(width) * usize::from(height);
    if !(10..=1024).contains(&width) || !(10..=1024).contains(&height) || area > 1_048_576 {
        return None;
    }
    if let Some(profile) = CUSTOM_FACE_PROFILES
        .iter()
        .find(|profile| profile.deployment_enabled && profile.width == width && profile.height == height)
    {
        return Some(*profile);
    }
    let max_frames = if area <= 8192 {
        20
    } else if area <= 76800 {
        10
    } else {
        5
    };
    Some(CustomFaceProfileSpec {
        code: 0,
        id: "custom",
        width,
        height,
        framebuffer_bytes: usize::from(width) * usize::from((height + 7) / 8),
        max_frames,
        max_group_bytes: 16 * 1024 * 1024,
        deployment_enabled: false,
    })
}

pub fn custom_face_profile_by_code(code: u16) -> Option<&'static CustomFaceProfileSpec> {
    CUSTOM_FACE_PROFILES
        .iter()
        .find(|profile| profile.code == code)
}
