/* generated by firmware/tools/generate-custom-face-device-protocol-contract.mjs */
pub const CUSTOM_FACE_DEVICE_PROTOCOL_VERSION: u16 = 1;
pub const CUSTOM_FACE_DEVICE_PACKAGE_BINARY_VERSION: u16 = 1;
pub const CUSTOM_FACE_DEVICE_MAX_RAW_CHUNK_BYTES: usize = 512;
pub const CUSTOM_FACE_DEVICE_MIN_LINE_BUFFER_BYTES: usize = 1_024;
pub const CUSTOM_FACE_DEVICE_ERROR_STORAGE: &str = "custom_face_storage_error";
pub const CUSTOM_FACE_DEVICE_ERROR_BUSY: &str = "device_busy";
